// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuMJL8i785Xbtl-3N-peKtp70UBakTKnw',
    appId: '1:858745284091:web:79428b3d6e6231fd39175e',
    messagingSenderId: '858745284091',
    projectId: 'flutter-ocr-def15',
    authDomain: 'flutter-ocr-def15.firebaseapp.com',
    storageBucket: 'flutter-ocr-def15.appspot.com',
    measurementId: 'G-X5BWZY0DVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwp_rLPORpItAEo6YPeA5jAOHndaM5X54',
    appId: '1:858745284091:android:8943c4dd6d40c32f39175e',
    messagingSenderId: '858745284091',
    projectId: 'flutter-ocr-def15',
    storageBucket: 'flutter-ocr-def15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FVtGEgdmZtXcumhjlpSYx7x8cBW8qKU',
    appId: '1:858745284091:ios:26e764aaafd0684539175e',
    messagingSenderId: '858745284091',
    projectId: 'flutter-ocr-def15',
    storageBucket: 'flutter-ocr-def15.appspot.com',
    iosClientId: '858745284091-p9246o3coaad9burnvrvqteel12pfcev.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrTesseract',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5FVtGEgdmZtXcumhjlpSYx7x8cBW8qKU',
    appId: '1:858745284091:ios:26e764aaafd0684539175e',
    messagingSenderId: '858745284091',
    projectId: 'flutter-ocr-def15',
    storageBucket: 'flutter-ocr-def15.appspot.com',
    iosClientId: '858745284091-p9246o3coaad9burnvrvqteel12pfcev.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrTesseract',
  );
}
